### ISSUE TITLE
Faire en sorte que le header du tableau soit toujours visible (sticky)

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2047]

**Comment by mxmeunier** [comment]
https://trello.com/c/QMNUUX2L/180-évolution-du-tableau-de-bord-possibilité-de-scroller-en-gardant-les-headers-en-fixe

**Comment by mxmeunier** [comment]
```css
table {
        border-collapse: collapse;
        width: 100%;
    }

    .test {
        /* fr-table already relative */
        /* position: relative; */
        height: 200px;
        overflow: auto;
    }

    .test th {
        position: sticky;
        top: 0;
        background-color: black;
        color: white;
    }
```
